# Setup
title:               (Title) #Wisconsin Autism Data Science Initiative
tagline:             #'(subtitle)'
description:         '(short description)' #'ADSI at UW-Madison'
url:                 https://cmdavis22.github.io
baseurl:             '/lanyon-test-website'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              #Mark Otto
  url:               #https://twitter.com/mdo
  email:             #markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
